#socrata
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/chicago.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/chicago.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/chicago.csv 0.4 "cbrb" > ../logs/chicago.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/utah.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/utah.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/utah.csv 0.4 "cbrb" > ../logs/utah.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/oregon.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/oregon.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/oregon.csv 0.4 "cbrb" > ../logs/oregon.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/gov.maryland.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/gov.maryland.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/gov.maryland.csv 0.4 "cbrb" > ../logs/gov.maryland.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/austintexas.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/austintexas.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/austintexas.csv 0.4 "cbrb" > ../logs/austintexas.log 2>&1

#wikipedia
#go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/politics.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/politics.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/politics.csv 0.4 "cbrb" > ../logs/politics.log 2>&1
#go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/education.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/education.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/education.csv 0.4 "cbrb" > ../logs/education.log 2>&1
#go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/military.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/military.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/military.csv 0.4 "cbrb" > ../logs/military.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/tv_and_film.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/tv_and_film.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/tv_and_film.csv 0.4 "cbrb" > ../logs/tv_and_film.log 2>&1
go run Test.go /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/football.json_index /data/changedata/roleMerging/final_experiments/cbrbInput/noDecay/football.json_query /data/changedata/roleMerging/final_experiments/cbrbResults/noDecay/football.csv 0.4 "cbrb" > ../logs/football.log 2>&1
